var myData = [
  {
    userName: 'BrianN',
    passWord: 'pwd',
    name: 'Brian Nations',
    score: 230,
    phNum: 9999998888,
    email: 'abc@efg.com',
    wanaPlay: 'yes',
    wanaShareLoc: 'no',
    wins: 2,
    losses: 3,
    image: 'http://placehold.it/230x230/000000'
  },
  {
    userName: 'RileyR',
    passWord: 'pwd',
    name: 'Riley Rose',
    score: 24,
    phNum: 9990009898,
    email: 'riley@gin.com',
    wanaPlay: 'yes',
    wanaShareLoc: 'yes',
    wins: 2,
    losses: 3,
    image: 'http://placehold.it/230x230/000000'
  },
  {
    userName: 'BileyR',
    passWord: 'pwd',
    name: 'Biley Rose',
    score: 289,
    phNum: 9993239898,
    email: 'biley@gin.com',
    wanaPlay: 'no',
    wanaShareLoc: 'no',
    wins: 2,
    losses: 3,
    image: 'http://placehold.it/230x230/000000'
  },
  {
    userName: 'Ramank',
    passWord: 'pwd',
    name: 'Raman Kumar',
    score: 12,
    phNum: 9993232398,
    email: 'rfgy@gin.com',
    wanaPlay: 'no',
    wanaShareLoc: 'no',
    wins: 2,
    losses: 3,
    image: 'http://placehold.it/230x230/000000'
  },
  {
    userName: 'Erin',
    passWord: 'pwd',
    name: 'Erin Lee',
    score: 279,
    phNum: 9234567898,
    email: 'erinl@gin.com',
    wanaPlay: 'no',
    wanaShareLoc: 'yes',
    wins: 2,
    losses: 3,
    image: 'http://placehold.it/230x230/000000'
  },
  {
    userName: 'Bhavyab',
    passWord: 'pwd',
    name: 'Bhavya Bharti',
    score: 65,
    phNum: 9334239898,
    email: 'bhavya@gin.com',
    wanaPlay: 'yes',
    wanaShareLoc: 'no',
    wins: 2,
    losses: 3,
    image: 'http://placehold.it/230x230/000000'
  }
];
